### ISSUE TITLE
Push data on the return leg

### ISSUE THREAD

**Issue by jernst** [consumer-reports-digital-lab/data-rights-protocol#5]
V0.2 seems to assume communication via HTTP, with:

* clients being either the Consumer, or the Authorized Agent on their behalf
* server being the Covered Business, or a service provider on their behalf.

In order for the Consumer or Authorized Agent to determine the status of the request, they need to repeatedly poll. Given that the Covered Business has a fairly long time to respond (weeks to months), that's a lot of polls.

I suggest that an (additional) alternate avenue is provided by which the Covered Business (or their service provider) can notify the Authorized Agent, or the Consumer, through an HTTP request in the other direction (where the Covered business is the client, and the Authorized Agent, or the Consumer, the HTTP server). This may be optional in case a Consumer, for example, does not have a suitable endpoint. In which case they should probably be notified anyway, such as by e-mail.

**Comment by rrix** [comment]
Hi Johannes! Thanks for the early feedback on this protocol work.

We've just prepared a new protocol version v.0.3 which adds a push-based callback channel like what you are describing. You can see that in the current specification doc, [section 2.04][1]. Each data rights request will be able to specify a callback URL when submitting the initial exercise request and will receive a POST to that URL, with the body of the request containing the new status of the request.

[1]: https://github.com/consumer-reports-digital-lab/data-rights-protocol/blob/main/data-rights-protocol.md#204-post-status_callback-data-rights-status-callback-endpoint

**Comment by rrix** [comment]
#
