### ISSUE TITLE
API Authentication redux

### ISSUE THREAD

**Issue by rrix** [consumer-reports-digital-lab/data-rights-protocol#54]
We have been working on proposals for this, this issue will track:

- [ ] API authentication
- [ ] identity token trust chain
- [ ] bilateral discovery mechanism (AAs can discover businesses implementing DRP, businesses access a list of AAs in the data rights network)

**Comment by dazzaji** [comment]
Perhaps the service discovery mechanism is somewhere between 0.8 and 1.2 or 1.3?  Especially if the beta phase is sufficient for production for a while.
